---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: kube-dump
  name: kube-dump
  namespace: kube-dump
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-dump
          containers:
            - name: kube-dump
              image: woozymasta/kube-dump:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: kube-dump
              env:
                - name: MODE
                  value: "dump-namespaces"
                - name: NAMESPACES
                  value: "dev,prod"
                - name: GIT_PUSH
                  value: "true"
                - name: GIT_BRANCH
                  value: "my-cluster"
          restartPolicy: OnFailure
