---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: kube-dump
  name: kube-dump
  namespace: kube-dump
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-dump
          containers:
            - name: kube-dump
              image: woozymasta/kube-dump:1.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: kube-dump
              env:
                - name: MODE
                  value: "dump"
                - name: GIT_PUSH
                  value: "true"
                - name: GIT_BRANCH
                  value: "k8s-cluster"
                - name: GIT_REMOTE_URL
                  value: "git@gitdp.zyfra.com/maxim.levchenko/main-k8s-backup.git"
              volumeMounts:
                - name: key
                  mountPath: /root/.ssh/id_ed25519
                  subPath: id_ed25519
                  readOnly: true
                - name: key-pub
                  mountPath: /root/.ssh/id_ed25519.pub
                  subPath: id_ed25519.pub
                  readOnly: true
              resources:
                limits:
                  cpu: 500m
                  memory: 200Mi
                requests:
                  cpu: 200m
                  memory: 100Mi
          restartPolicy: OnFailure
          volumes:
            - name: key
              secret:
                secretName: kube-dump-key
                items:
                  - key: kube-dump
                    path: id_ed25519
            - name: key-pub
              secret:
                secretName: kube-dump-key
                items:
                  - key: kube-dump.pub
                    path: id_ed25519.pub
